/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Laptop.glb -T 
Files: .\Laptop.glb [21.42MB] > C:\Users\Umar\code\portfolio\public\models\Laptop-transformed.glb [1.2MB] (94%)
Author: Jiahui QIU (https://sketchfab.com/jiahuiqiu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-concept-81498159661a48479bcceadc37fe36b8
Title: Laptop Concept
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Laptop(props) {
  const { nodes, materials } = useGLTF('/models/Laptop-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_6.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/Laptop-transformed.glb')
