/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\Laptop.glb -T 
Files: .\Laptop.glb [702.48KB] > C:\Users\Umar\code\portfolio\public\models\Laptop-transformed.glb [92.56KB] (87%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Laptop(props) {
  const { nodes, materials } = useGLTF('/models/Laptop-transformed.glb')  
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_322.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/Laptop-transformed.glb')
